architecture: 'xnet' #xnet or unet

tile dir: '<YOUR_PATH>/tiles/'
label dir: '<YOUR_PATH>/labels/'

model dir: '<YOUR_PATH>/naive_segmentation/models/'
model name: 'example'

training parameters:
  train names: '<YOUR_PATH>/train_idx_fname.csv'
  val names: '<YOUR_PATH>/valid_idx_fname.csv'
  filter depth:
    0: 16
    1: 32
    2: 64
    3: 128
    4: 0
  batch size: 3
  epochs before ES: 1
  epochs after ES: 10
  steps per epoch: 1
  validation steps: 1
  class weights:
    background: 1
    flood: 1

testing parameters:
  test names: '<YOUR_PATH>/test_idx_fname.csv'
